// Autogenerated by @fig/complete-commander

const completionSpec: Fig.Spec = {
  name: "ethernaut",
  description: "Ethereum swiss army knife/game/tool/superweapon",
  subcommands: [
    {
      name: "config",
      description: "Configure the Ethernaut CLI",
      subcommands: [
        {
          name: "provider",
          description: "Manage the CLI's Ethereum provider",
          subcommands: [
            {
              name: "add-provider",
              description: "Add an Ethereum provider",
              options: [
                {
                  name: ["-h", "--help"],
                  description: "display help for command",
                  priority: 49,
                },
              ],
              args: [
                {
                  name: "provider",
                  description: "Provider to add",
                  isOptional: true,
                },
              ],
            },
            {
              name: "remove-provider",
              description: "Remove an Ethereum provider",
              options: [
                {
                  name: ["-h", "--help"],
                  description: "display help for command",
                  priority: 49,
                },
              ],
              args: [
                {
                  name: "provider",
                  description: "Provider to remove",
                  isOptional: true,
                },
              ],
            },
            {
              name: "set-provider",
              description: "Set an Ethereum provider",
              options: [
                {
                  name: ["-h", "--help"],
                  description: "display help for command",
                  priority: 49,
                },
              ],
              args: [
                {
                  name: "provider",
                  description: "Provider to set",
                  isOptional: true,
                },
              ],
            },
            {
              name: "help",
              description: "display help for command",
              priority: 49,
              args: { name: "command", isOptional: true, template: "help" },
            },
          ],
          options: [
            {
              name: ["-h", "--help"],
              description: "display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "show",
          description: "Show all current config properties",
          options: [
            {
              name: ["-h", "--help"],
              description: "display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "help",
          description: "display help for command",
          priority: 49,
          args: { name: "command", isOptional: true, template: "help" },
        },
      ],
      options: [
        {
          name: ["-h", "--help"],
          description: "display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "interact",
      description: "Interacts with a contract",
      options: [
        {
          name: ["-h", "--help"],
          description: "display help for command",
          priority: 49,
        },
      ],
      args: [
        {
          name: "nameOrAddress",
          description: "The name or address of the contract",
          isOptional: true,
        },
      ],
    },
    {
      name: "util",
      description: "Utilities for Ethereum hackers",
      subcommands: [
        {
          name: "to-bytes",
          description: "Converts stuff to bytes32",
          options: [
            {
              name: ["-h", "--help"],
              description: "display help for command",
              priority: 49,
            },
          ],
          args: [
            {
              name: "value",
              description: "Value to convert",
              isOptional: true,
            },
          ],
        },
        {
          name: "to-string",
          description: "Converts bytes32 to string",
          options: [
            {
              name: ["-h", "--help"],
              description: "display help for command",
              priority: 49,
            },
          ],
          args: [
            {
              name: "value",
              description: "Value to convert",
              isOptional: true,
            },
          ],
        },
        {
          name: "tx-info",
          description: "Retrieves information about a transaction",
          options: [
            {
              name: ["-h", "--help"],
              description: "display help for command",
              priority: 49,
            },
          ],
          args: [
            {
              name: "tx-hash",
              description: "Transaction hash",
              isOptional: true,
            },
          ],
        },
        {
          name: "unit",
          description: "Converts between different units of Ether",
          options: [
            {
              name: ["-f", "--from"],
              description: "Convert from this unit",
              args: {
                name: "from",
                suggestions: [
                  "wei",
                  "ether",
                  "kwei",
                  "mwei",
                  "gwei",
                  "szabo",
                  "finney",
                ],
              },
            },
            {
              name: ["-d", "--to"],
              description: "Convert to this unit",
              args: {
                name: "to",
                suggestions: [
                  "wei",
                  "ether",
                  "kwei",
                  "mwei",
                  "gwei",
                  "szabo",
                  "finney",
                ],
              },
            },
            {
              name: ["-h", "--help"],
              description: "display help for command",
              priority: 49,
            },
          ],
          args: [
            {
              name: "value",
              description: "Value to convert",
              isOptional: true,
            },
          ],
        },
        {
          name: "help",
          description: "display help for command",
          priority: 49,
          args: { name: "command", isOptional: true, template: "help" },
        },
      ],
      options: [
        {
          name: ["-h", "--help"],
          description: "display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "help",
      description: "display help for command",
      priority: 49,
      args: { name: "command", isOptional: true, template: "help" },
    },
  ],
  options: [
    { name: ["-V", "--version"], description: "output the version number" },
    {
      name: ["-h", "--help"],
      description: "display help for command",
      priority: 49,
    },
  ],
};

export default completionSpec;
